### ISSUE TITLE
2024-5-26，如果设置浏览器为半屏显示，在coze的bot页面无法完整显示对话区

### ISSUE THREAD

**Issue by GoTop** [xx025/strawberry#6]
<img width="1920" alt="Screenshot 2024-05-26 at 10 54 02" src="https://github.com/xx025/strawberry/assets/1784319/b99c3d1e-497f-40dc-90f2-245246c3cc33">

**Comment by xx025** [comment]
这个问题已经解决

当半屏状态下可以使用扩展按钮，此时仅显示聊天框，有更好的可视化效果


![image](https://github.com/xx025/strawberry/assets/71559822/57d50699-da8a-45ab-9403-4159f022edc2)

**Comment by GoTop** [comment]
感谢，修复后效果很好
